### ISSUE TITLE
How do I find a user's banner using the plugin?

### ISSUE THREAD

**Issue by KainesLaw** [Skamt/BDAddons#10]
I don't see a banner button to view a user's banner, only a button to see their profile picture. Am I blind?

**Comment by Skamt** [comment]
If you look at the [previews](https://github.com/Skamt/BDAddons/tree/main/ViewProfilePicture#preview) you can see that there are side buttons that'll let you switch between the banner and the profile picture.

**Comment by KainesLaw** [comment]
I don't see that option. That's why I created this issue request.

**Comment by KainesLaw** [comment]
I don't have anything in my Custom CSS, nor do I have a theme on. The only thing I can think of is the plugin I have called [ImageUtilities](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ImageUtilities/). Do you think that might be messing with it?

**Comment by Skamt** [comment]
Yup, i just tested it and it seems to do so. Sadly **ImageUtilities** is not compatible with **VPP** and it's not an issue on my end, **ImageUtilities** overrides the whole previous/next functionality.

**Comment by KainesLaw** [comment]
In your opinion, should I even use it?
