### ISSUE TITLE
Concerns about abuse of Plugin.

### ISSUE THREAD

**Issue by EbonyDream** [Skamt/BDAddons#11]
I feel like some features should be removed as it makes it super easy for people to copy and save the profile pictures to use for themselves without the persons permission. Which if it's some random image off the internet it's fine. Yet some people draw their own profile pictures or commission someone to draw one for them and this could allow people to steal other people's art. Which might not be everyone but even a few misusing it isn't good.

**Comment by Skamt** [comment]
Abuse regarding having the ability to save a pictures off the internet, What?


There's already an infinite number of ways for people to save someone's discord profile picture. This plugin does not offer ground breaking tech for saving pictures, and it is only available for the few people who use it and the few people who use BD.

You can try exploring any browser's extension store for extensions that allows you to do the exact same, or maybe **approved** discord bots that let you run a command to grab someone's avatar.
