### ISSUE TITLE
[Request] [LazyLoadChannels] Double click for loading channels

### ISSUE THREAD

**Issue by themegaxandy** [Skamt/BDAddons#13]
I have a suggestion. Instead of clicking on a channel, and then moving the mouse to click the load channel button, the user could just double-click on the channel, which would be faster and more practical.

**Comment by Skamt** [comment]
I've tried this, and it's somewhat of a pain in certain places, though something like clicking while holding Control or Shift seems more plausible.

**Comment by themegaxandy** [comment]
That should do the trick
