### ISSUE TITLE
[Suggestion] [CopyImageLink]

### ISSUE THREAD

**Issue by RuneDemomn** [Skamt/BDAddons#19]
Can this also be applied to videos? Currently this only creates a 'copy link' button for GIFs and images, and having this option, or at least a toggle option, would be nice for videos shared on discord too.

**Comment by Skamt** [comment]
Well, you generally don't see videos open up in modals like images do, so there isn't a nice enough place to put a `copy link` button.

also the plugin called `CopyImageLink` it's meant for images, if i were to do this, i would instead take this plugin down, and write a new one for all purpose copy plugin, which there's already one, though i'm not sure if it's still working.
