### ISSUE TITLE
cannot send animated stickers

### ISSUE THREAD

**Issue by TrungHieu123s** [Skamt/BDAddons#20]
I am using BetterDiscord to add this plugin and when i clicked on a animated sticker is says 
<img width="340" alt="image" src="https://github.com/Skamt/BDAddons/assets/97725120/72c4edbb-ee7a-415f-a0cf-049086a89df2">
Then i checked the setting and it says
<img width="481" alt="image" src="https://github.com/Skamt/BDAddons/assets/97725120/8d73643b-ea07-4f5e-8365-48e7ebf2d027">

**Comment by Skamt** [comment]
fixed in [a4f272d](https://github.com/Skamt/BDAddons/commit/a4f272d93123b1f4f709edda88d89d57238dc0b7) wait approval
