### ISSUE TITLE
[BUG] UNABLE TO SEND SENDABLE STICKER. (SendStickersAsLinks.plugin.js)

### ISSUE THREAD

**Issue by AsahiOw** [Skamt/BDAddons#21]
Describe the bug:
Can not send stickers that are available on that server

To Reproduce:
Click on the sticker that is available on that server while the plugin is on

-Enable SendStickersAsLinks.plugin.js.
-Go to any server.
-Choose a Sticker that is from the server you are chatting in.
-Click on that sticker but nothing happens.

Client:

Desktop [Windows 10 64-Bit (10.0.22621)]
Discord Build Channel [Stable 249740 (9e2b64f)]
Plugin Version [2.2.3]
BD Version [1.9.6]

**Comment by Skamt** [comment]
I can't reproduce the problem, could you check the console for any errors ?

**Comment by AsahiOw** [comment]
> I can't reproduce the problem, could you check the console for any errors ?

Ah it is from my end, the plugin conflict with one of my test plugin and both of them somehow block all Sendable Stickers when both are running. My bad Sorry.
