### ISSUE TITLE
Hi! I have a plugin request. + Also not seeing the benefits of Lazyloader

### ISSUE THREAD

**Issue by radientgradient** [Skamt/BDAddons#23]
Hi there Skamt, I use your other plugins and they work great. I noticed that you recently made that Lazyloader plugin, and I tried it. I'm not sure I see any difference because when I click into different categories/sections within a Discord server, that annoying freezing lag is still there when it supposedly shouldn't be, so it confuses me a bit. 

=--==

I also have a plugin idea:

Can you make a plugin to customize the right click > Favorited reactions menu? 
Here is what I mean: 
![image](https://github.com/Skamt/BDAddons/assets/152841276/358113d3-298b-470e-bd47-2dcb6f8a466f)

4 slots is very limited for quick-reaction access, and there is no way to edit which one gets shown either. It's just the top 4 favorited reactions which is poor discord base functionality.  Why is it only 4 in the quick access menu? It could be a longer bar.

On top of that... : 
![image](https://github.com/Skamt/BDAddons/assets/152841276/73c2de95-605b-425c-8a97-a613475e5b18)
There is no way to edit or repin any reactions either in the extended menu either. 

The only way to reorder them at all is by unfavoriting ALL reactions, and organizing them by refavoriting the chosen reactions/emojis first.

Would be nice to have a plugin to deal with this and I'm not sure why no one has ever tackled the issue!

**Comment by Skamt** [comment]
I don't do plugin suggestions, you're much better off asking in [Plugin Suggestion Board](https://discord.com/channels/86004744966914048/1060303248575172648)

All **LazyLoadChannels** does is stops channels from loading until the user choses to.
