### ISSUE TITLE
[Feature-Request] Option to have Lazy Loading to load chats once they are clicked on instead of waiting for confirmation

### ISSUE THREAD

**Issue by Shadowphoenix** [Skamt/BDAddons#24]
Basically the Title is the gist of it.
Maybe i am just misunderstanding what the plugin is supposed to do but: Clicking "Load Channel" every time leads to me wasting VASTLY more time clicking that button than whats saved by lazyloading to begin with. It is especially annoying if you frequent a lot of servers with lots of different channels that you only visit sporadically. 
I noticed a decrease in intial loading time when opening discord but the like 5 seconds i save initially are already lost again by just having to click the "load channel"-button twice. And whats the point of lazyloading when i have to set up autoloading for all the various channels?

So would be cool if there was an option to lazyload all channels but to load any channel when it is clicked on instead of waiting for the button to be pressed.

**Comment by Skamt** [comment]
It sounds like this plugin isn't for you.

**Comment by Shadowphoenix** [comment]
Fair enough, i might reconsider using it then :)
