### ISSUE TITLE
No option for disabling autoload for DMs once it has been enabled

### ISSUE THREAD

**Issue by Theswearhole** [Skamt/BDAddons#25]
there is no option to disable autoloading DMs once you have enabled it
![Untitled-1](https://github.com/Skamt/BDAddons/assets/87924864/4ee9876d-0e20-44cd-9f3c-544868371efa)

**Comment by Theswearhole** [comment]
Disabling and enabling the lazy load of DMs setting doesn't even reset it

**Comment by Skamt** [comment]
This have gone missing for a long time lol, I'll fix it. 


> Disabling and enabling the "lazy load DMs" setting doesn't even reset it

and it shouldn't.

**Comment by Skamt** [comment]
fixed 33d633c
