### ISSUE TITLE
ViewProfilePicture avatar goes beyond the boundaries of the screen

### ISSUE THREAD

**Issue by Serega007RU** [Skamt/BDAddons#26]
ViewProfilePicture avatar goes beyond the boundaries of the screen
This is what it looks like for me
![image](https://github.com/Skamt/BDAddons/assets/64780091/529651cf-f879-4119-8f28-98db8bc7f044)
here's what the image actually looks like
![image](https://github.com/Skamt/BDAddons/assets/64780091/79233d6f-92b4-480e-a306-397e5939189a)

If you compare these 2 images, you can see that in the first image the lower part is cropped.
This is a problem with any avatar and any user I'm watching

**Comment by Skamt** [comment]
weird, discord's own Image component used to resize the image, they might have borked something? idk, i'll look into it as soon as possible.
