### ISSUE TITLE
LazyLoadChannelse

### ISSUE THREAD

**Issue by Miyuki-10** [Skamt/BDAddons#28]
if i scroll far up in dms messages, i cannot see old messages, i can max see like 60 ish messages, even there should be thousands, i should still try to load if i scroll up and only load recent ones if i don't scroll up

**Comment by Skamt** [comment]
I can't reproduce this.
Did you try disabling the plugin and see if the issue persists ?

**Comment by Skamt** [comment]
Weird, i have absolutely no idea what could cause that, never happened to me, i guess we'll have to wait until someone else runs into the same issue
