### ISSUE TITLE
SendStickersAsLinks non-animated stickers

### ISSUE THREAD

**Issue by Eight-P** [Skamt/BDAddons#30]
When "Highlight animated stickers" is enabled, all types of stickers are highlighted.
When "Send animated stickers" is disabled, no sticker can be sent, including non-animated ones.

It seems to me like all stickers are detected as animated, even when they are not.

SendStickersAsLinks v2.2.4
Win 10 Stable 284422

**Comment by Skamt** [comment]
Should be fixed once the update is approved.
