### ISSUE TITLE
ViewProfilePicture is not working

### ISSUE THREAD

**Issue by dhimautomoputra** [Skamt/BDAddons#32]
No button to view users's avatar and banner

**Comment by marto05** [comment]
The button stopped appearing.

**Comment by Skamt** [comment]
This is probably the new profile popouts feature rolling out to some users, Could you also provide your discord version

**Comment by dhimautomoputra** [comment]
Yeah, I got this new UI like weeks ago. Here is my discord version:

Discord Info
Stable 299899 (269870d)
Host 1.0.9148 x64 (48468)
Windows 11 64-bit (10.0.22631)

BetterDiscord
Stable 1.10.1

**Comment by Skamt** [comment]
yeah if it's the new UI, i can't do anything about it until i get, im sorry :cry:

**Comment by dhimautomoputra** [comment]
The button still appear if I do personal message, so I need to do that if I want to lol. The problem is when I click someone's profile from server, this new UI things made the button disappear. That's okay, thank you for your response and I hope you will get it asap.
![Screenshot 2024-06-07 174824](https://github.com/Skamt/BDAddons/assets/20907306/fe1d95ca-2d6f-4c02-af6f-9d5d15e4a353)

**Comment by dhimautomoputra** [comment]
Just want to let you know that I have an update for my Discord. For now here is my version:

Discord Info
stable 301409 (2506b34)
Host 1.0.9149 x64 (48589)
Windows 11 64-bit (10.0.22631)

BetterDiscord
Stable 1.10.1

This version still has the same UI that I got from previous version (Stable 299899 (269870d)). Hope you got the update as well so you can fix the issue.

Thanks!

**Comment by Skamt** [comment]
I thought it would relate to the discord version, but they're just painfully slowly pushing it to people :sob:

**Comment by dhimautomoputra** [comment]
The fastest way is you need to have an access with that kind of account. Unfortunately, only my main account does. So we just wait till the time is come

**Comment by Ykkt** [comment]
Since the last update, the plugin does not load

![Screenshot_1](https://github.com/Skamt/BDAddons/assets/24494149/079ad691-a08b-4eee-9c6b-3aad83137a37)

Code:

TypeError: Cannot read properties of undefined (reading 'ImageModal')
    at eval (betterdiscord://plugins/ViewProfilePicture.plugin.js:240:41)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by ROMAiev** [comment]
> An update is out fixing the recent break.

Even after updating the error persisted, I deleted the files, downloaded them again and the error disappeared, thank you

**Comment by Skamt** [comment]
fixed in 4e79629
