### ISSUE TITLE
ViewProfilePicture Button Not Showing

### ISSUE THREAD

**Issue by richardkapp12** [Skamt/BDAddons#37]
The button which shows the image and banner doesn't appear anymore on the new discord layout of profiles. 

For bots the button is there. However, on user profiles it's not.

See example below:
<img width="498" alt="SCR-20240620-ldxw" src="https://github.com/Skamt/BDAddons/assets/85017563/a071be6d-76a6-4590-9e01-5e2a5210861b">
<img width="493" alt="SCR-20240620-lekr" src="https://github.com/Skamt/BDAddons/assets/85017563/fe7eb6f0-fc8a-4edf-bd7b-08d1c28f07c8">

**Comment by Skamt** [comment]
#32
