### ISSUE TITLE
[Bug] ViewProfilePicture Crash

### ISSUE THREAD

**Issue by maenDisease** [Skamt/BDAddons#4]
Clicking on the VPP button causes a crash. Currently only affects Discord PTB and Canary
![image](https://user-images.githubusercontent.com/90428263/210634259-2d06daf7-3d8f-4f1c-bb16-653f77baf2d4.png)

**Comment by Skamt** [comment]
Fixed [0877a7f](https://github.com/Skamt/BDAddons/commit/0877a7f92479d8a5554b0591195459657d39c854)
waiting approval.
