### ISSUE TITLE
[Bug] ViewProfilePicture no longer working after Discord update

### ISSUE THREAD

**Issue by Lupus47** [Skamt/BDAddons#40]
I had a Discord update where BetterDiscord stopped working and had to be reinstalled. Along with this a few plugins haven't been updated and will not work, including ViewProfilePicture. I really liked this plugin. 

Here is a photo showing the error in the plugins section of the settings menu:
![Screenshot 2024-06-30 001119](https://github.com/Skamt/BDAddons/assets/123925035/1ee7a417-b9c4-4052-be5a-7320f4a0ddf5)

It also warns me of the error on startup of Discord. I don't know enough about CSS or JS to fix it myself.
Any advice or help is appreciated,
Thank You.

**Comment by Skamt** [comment]
before posting an issue, look through closed issues to see if a similar issue has been posted and resolved.

A fix has been pushed. we just waiting for it to be approved.

![image](https://github.com/Skamt/BDAddons/assets/114232893/45eec486-86e2-47e6-8a39-98e806a2795c)
