### ISSUE TITLE
SendStickersAsLinks won't load.

### ISSUE THREAD

**Issue by MagmaBro123** [Skamt/BDAddons#45]
Title.

![image](https://github.com/user-attachments/assets/dace3206-e35a-40f4-bc07-223357c201fa)

**Comment by emanonwanderer** [comment]
also having the same issue, tried restarting and redownloading to no avail
![stickerlinks error](https://github.com/user-attachments/assets/0e1e8a65-c1f2-4d79-9c01-e20df751b69b)
