### ISSUE TITLE
plugin not loading after the latest discord update

### ISSUE THREAD

**Issue by 2beyajay** [Skamt/BDAddons#48]
Seeing the following error when loading the js

TypeError: zustand is not a function
    at eval (betterdiscord://plugins/SendStickersAsLinks.plugin.js:96:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201

**Comment by 2beyajay** [comment]
This is marked completed but it's still happening. Not fixed.

**Comment by mmupmip** [comment]
True

**Comment by 2beyajay** [comment]
> True Edit: Nvm just update the plugin with the new version, sorry.

How do i update it when the plugin won't even load on better discord? And on betterdiscord's website it says that the plugin was last updated in July. Where to get the latest?

**Comment by mmupmip** [comment]
Download new js file in this repo

**Comment by 2beyajay** [comment]
> Download new js file in this repo

Yep, just did. Was about to come here to say thanks. Cheers.
