### ISSUE TITLE
plugin doesnt work

### ISSUE THREAD

**Issue by jaysuna** [Skamt/BDAddons#52]
no errors, the button is there but when i click on it, it doesnt open the pfp/banner

**Comment by fowlis** [comment]
I have arrived with something useful(?).
Error that appears in console when trying the "View profile picture" button:
![image](https://github.com/user-attachments/assets/975e0eb2-5449-45a8-a276-0f84b3b10cd5)

**Comment by Skamt** [comment]
been fixed, wait approval

**Comment by jaysuna** [comment]
works bro ty
