### ISSUE TITLE
Plugin will not load?

### ISSUE THREAD

**Issue by ThorinStarchaser** [Skamt/BDAddons#54]
the plugin just refuses to load for me saying there is a blank space where there isn't supposed to be but I can't seem to find it? could someone just look over the code?

**Comment by ThorinStarchaser** [comment]
![Screenshot 2024-11-13 062852](https://github.com/user-attachments/assets/2458aa31-ab92-4291-8179-175049b46489)

here is what I get from discord

**Comment by jaysuna** [comment]
same i have this issue

**Comment by rubyatmidnight** [comment]
1.2.14 works for me.

**Comment by FazePas** [comment]
> ![Screenshot 2024-11-13 062852](https://private-user-images.githubusercontent.com/123475826/385604259-2458aa31-ab92-4291-8179-175049b46489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA3OTUsIm5iZiI6MTczMTgzMDQ5NSwicGF0aCI6Ii8xMjM0NzU4MjYvMzg1NjA0MjU5LTI0NThhYTMxLWFiOTItNDI5MS04MTc5LTE3NTA0OWI0NjQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwODAxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDcxNDJjZjMxNTNhNjMyMGY2MGVmOTAyZDI4MWU1ZTljMzE1MmEwODEzN2EzMTkzMGU0OWQ5MWRlMDE3NjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IJ8LlyWU1J9oOF3XeR2c_JsI4aTsMkpCboFtz_zmRho)
> 
> here is what I get from discord

same error

**Comment by DanTVD** [comment]
same here

**Comment by Pysis868** [comment]
I'd say close as duplicate with #53.
