### ISSUE TITLE
Emojis Plugin doesn't work

### ISSUE THREAD

**Issue by eeNPeeCee** [Skamt/BDAddons#55]
![image_2024-11-14_133331848](https://github.com/user-attachments/assets/cb0e77a8-848e-4560-964d-ebf0cf595589)
Updated all plugins and specifically the emoji one won't load properly, has been happening for the past 3 versions might be something with my discord specifically

**Comment by Skamt** [comment]
Do not open issues concerning Emoji plugin. it is only for personal use.

You may ping me about it in the BD server, but that's about it.
