### ISSUE TITLE
LazyLoadChannels zustand is not a function

### ISSUE THREAD

**Issue by slysnake96** [Skamt/BDAddons#56]
As mentioned in the title, I get an error for LazyLoadChannels that says "zustand is not a function"
![2024-11-22 07_25_03-Friends - Discord](https://github.com/user-attachments/assets/dbf461f9-4fe5-4b60-9618-e1868411b03c)

**Comment by emanonwanderer** [comment]
same issue here
![image](https://github.com/user-attachments/assets/afeb18b5-de7e-4c5a-a709-5b65ea986929)

**Comment by Skamt** [comment]
been fixed, wait for approval or grab the plugins from the repo.
