### ISSUE TITLE
something wrong in the code

### ISSUE THREAD

**Issue by castkolife** [Skamt/BDAddons#57]
when i add the ,,send stickers as links" a problem appears and tells me there is something wrong in the code this in the code: TypeError: zustand is not a function
    at eval (betterdiscord://plugins/SendStickersAsLinks.plugin.js:83:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201 and i dont know how to code :) so the help is apreciated

**Comment by Pysis868** [comment]
Similar to #53 and #54, I upgraded base Discord, and receive similar error.

TypeError: zustand is not a function
    at eval (betterdiscord://plugins/ViewProfilePicture.plugin.js:81:2)
    at PluginManager.requireAddon (betterdiscord/renderer.js:6390:7)
    at PluginManager.loadAddon (betterdiscord/renderer.js:1939:20)
    at PluginManager.loadAddon (betterdiscord/renderer.js:6306:25)
    at betterdiscord/renderer.js:1832:41

`const filter = Filters.byStrings("createWithEqualityFn");`:
>  filter
<- module => {
      if (!(module !== null && module !== void 0 && module.toString) || typeof (module === null || module === void 0 ? void 0 : module.toString) !== "function") return; // Not stringable

>  Object.entries(modules)
<- (16934) [Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), …]
  > [0 … 9999]
  > [10000 … 16933]
    length: 16934
  > [[Prototype]]: Array(0)

// const modules = Api.Webpack.modules;

>  Object.entries(modules).slice(-10).map(pair=>pair[0])
<- (10) ['999483', '999532', '999534', '999568', '999632', '999650', '999671', '999718', '999923', '999991']

>  Object.entries(modules).slice(-10).map(pair=>pair[1])
<- (10) [ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ]

Some function examples from this file:
`https://discord.com/assets/423c6c07046f4f5deec9.js`

I found the similarly named function `createWithContent` in `https://discord.com/assets/d24ff21d75611327e3b1.js`, named with the integer `133092` instead, if that is applicable.

Environment:
```
Stable 347699 (5cba0fe)
Host 0.0.76 x64 Build Override: N/A
Linux 64-bit (6.11.6-200.fc40.x86_64)
```
